package models;
// Generated Nov 19, 2019 8:38:44 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChiTietGioHang generated by hbm2java
 */
@Entity
@Table(name="ChiTietGioHang"
    ,schema="dbo"
    ,catalog="JAVA_WEB"
)
public class ChiTietGioHang  implements java.io.Serializable {


     private ChiTietGioHangId id;
     private Giay giay;
     private GioHang gioHang;
     private Integer soLuong;
     private Integer giaTien;
     private Integer giamGia;

    public ChiTietGioHang() {
    }

	
    public ChiTietGioHang(ChiTietGioHangId id, Giay giay, GioHang gioHang) {
        this.id = id;
        this.giay = giay;
        this.gioHang = gioHang;
    }
    public ChiTietGioHang(ChiTietGioHangId id, Giay giay, GioHang gioHang, Integer soLuong, Integer giaTien, Integer giamGia) {
       this.id = id;
       this.giay = giay;
       this.gioHang = gioHang;
       this.soLuong = soLuong;
       this.giaTien = giaTien;
       this.giamGia = giamGia;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="maGioHang", column=@Column(name="MaGioHang", nullable=false) ), 
        @AttributeOverride(name="maGiay", column=@Column(name="MaGiay", nullable=false) ) } )
    public ChiTietGioHangId getId() {
        return this.id;
    }
    
    public void setId(ChiTietGioHangId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaGiay", nullable=false, insertable=false, updatable=false)
    public Giay getGiay() {
        return this.giay;
    }
    
    public void setGiay(Giay giay) {
        this.giay = giay;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaGioHang", nullable=false, insertable=false, updatable=false)
    public GioHang getGioHang() {
        return this.gioHang;
    }
    
    public void setGioHang(GioHang gioHang) {
        this.gioHang = gioHang;
    }

    
    @Column(name="SoLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

    
    @Column(name="GiaTien")
    public Integer getGiaTien() {
        return this.giaTien;
    }
    
    public void setGiaTien(Integer giaTien) {
        this.giaTien = giaTien;
    }

    
    @Column(name="GiamGia")
    public Integer getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(Integer giamGia) {
        this.giamGia = giamGia;
    }




}


