package models;
// Generated Nov 19, 2019 8:38:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Giay generated by hbm2java
 */
@Entity
@Table(name="Giay"
    ,schema="dbo"
    ,catalog="JAVA_WEB"
)
public class Giay  implements java.io.Serializable {


     private int maGiay;
     private HangGiay hangGiay;
     private LoaiGiay loaiGiay;
     private String tenGiay;
     private String tieuDe;
     private Integer gia;
     private Integer giamGia;
     private Integer soLuong;
     private Set<ChiTietGioHang> chiTietGioHangs = new HashSet<ChiTietGioHang>(0);
     private Set<ChiTietHoaDon> chiTietHoaDons = new HashSet<ChiTietHoaDon>(0);
     private Set<DanhGia> danhGias = new HashSet<DanhGia>(0);
     private ThongTinCoBan thongTinCoBan;

    public Giay() {
    }

	
    public Giay(int maGiay) {
        this.maGiay = maGiay;
    }
    public Giay(int maGiay, HangGiay hangGiay, LoaiGiay loaiGiay, String tenGiay, String tieuDe, Integer gia, Integer giamGia, Integer soLuong, Set<ChiTietGioHang> chiTietGioHangs, Set<ChiTietHoaDon> chiTietHoaDons, Set<DanhGia> danhGias, ThongTinCoBan thongTinCoBan) {
       this.maGiay = maGiay;
       this.hangGiay = hangGiay;
       this.loaiGiay = loaiGiay;
       this.tenGiay = tenGiay;
       this.tieuDe = tieuDe;
       this.gia = gia;
       this.giamGia = giamGia;
       this.soLuong = soLuong;
       this.chiTietGioHangs = chiTietGioHangs;
       this.chiTietHoaDons = chiTietHoaDons;
       this.danhGias = danhGias;
       this.thongTinCoBan = thongTinCoBan;
    }
   
     @Id 

    
    @Column(name="MaGiay", unique=true, nullable=false)
    public int getMaGiay() {
        return this.maGiay;
    }
    
    public void setMaGiay(int maGiay) {
        this.maGiay = maGiay;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaHang")
    public HangGiay getHangGiay() {
        return this.hangGiay;
    }
    
    public void setHangGiay(HangGiay hangGiay) {
        this.hangGiay = hangGiay;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MaLoaiGiay")
    public LoaiGiay getLoaiGiay() {
        return this.loaiGiay;
    }
    
    public void setLoaiGiay(LoaiGiay loaiGiay) {
        this.loaiGiay = loaiGiay;
    }

    
    @Column(name="TenGiay")
    public String getTenGiay() {
        return this.tenGiay;
    }
    
    public void setTenGiay(String tenGiay) {
        this.tenGiay = tenGiay;
    }

    
    @Column(name="TieuDe")
    public String getTieuDe() {
        return this.tieuDe;
    }
    
    public void setTieuDe(String tieuDe) {
        this.tieuDe = tieuDe;
    }

    
    @Column(name="Gia")
    public Integer getGia() {
        return this.gia;
    }
    
    public void setGia(Integer gia) {
        this.gia = gia;
    }

    
    @Column(name="GiamGia")
    public Integer getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(Integer giamGia) {
        this.giamGia = giamGia;
    }

    
    @Column(name="SoLuong")
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="giay")
    public Set<ChiTietGioHang> getChiTietGioHangs() {
        return this.chiTietGioHangs;
    }
    
    public void setChiTietGioHangs(Set<ChiTietGioHang> chiTietGioHangs) {
        this.chiTietGioHangs = chiTietGioHangs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="giay")
    public Set<ChiTietHoaDon> getChiTietHoaDons() {
        return this.chiTietHoaDons;
    }
    
    public void setChiTietHoaDons(Set<ChiTietHoaDon> chiTietHoaDons) {
        this.chiTietHoaDons = chiTietHoaDons;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="giay")
    public Set<DanhGia> getDanhGias() {
        return this.danhGias;
    }
    
    public void setDanhGias(Set<DanhGia> danhGias) {
        this.danhGias = danhGias;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="giay")
    public ThongTinCoBan getThongTinCoBan() {
        return this.thongTinCoBan;
    }
    
    public void setThongTinCoBan(ThongTinCoBan thongTinCoBan) {
        this.thongTinCoBan = thongTinCoBan;
    }




}


