package models;
// Generated Nov 19, 2019 8:38:44 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HangGiay generated by hbm2java
 */
@Entity
@Table(name="HangGiay"
    ,schema="dbo"
    ,catalog="JAVA_WEB"
)
public class HangGiay  implements java.io.Serializable {


     private int maHang;
     private String tenHangGiay;
     private String ghichu;
     private Set<Giay> giays = new HashSet<Giay>(0);

    public HangGiay() {
    }

	
    public HangGiay(int maHang) {
        this.maHang = maHang;
    }
    public HangGiay(int maHang, String tenHangGiay, String ghichu, Set<Giay> giays) {
       this.maHang = maHang;
       this.tenHangGiay = tenHangGiay;
       this.ghichu = ghichu;
       this.giays = giays;
    }
   
     @Id 

    
    @Column(name="MaHang", unique=true, nullable=false)
    public int getMaHang() {
        return this.maHang;
    }
    
    public void setMaHang(int maHang) {
        this.maHang = maHang;
    }

    
    @Column(name="TenHangGiay")
    public String getTenHangGiay() {
        return this.tenHangGiay;
    }
    
    public void setTenHangGiay(String tenHangGiay) {
        this.tenHangGiay = tenHangGiay;
    }

    
    @Column(name="Ghichu")
    public String getGhichu() {
        return this.ghichu;
    }
    
    public void setGhichu(String ghichu) {
        this.ghichu = ghichu;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hangGiay")
    public Set<Giay> getGiays() {
        return this.giays;
    }
    
    public void setGiays(Set<Giay> giays) {
        this.giays = giays;
    }




}


