package models;
// Generated Nov 19, 2019 8:38:44 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiGiay generated by hbm2java
 */
@Entity
@Table(name = "LoaiGiay",
         schema = "dbo",
         catalog = "JAVA_WEB"
)
public class LoaiGiay implements java.io.Serializable {

    private int maLoaiGiay;
    private String tenLoaiGiay;
    private Set<Giay> giays = new HashSet<Giay>(0);

    public LoaiGiay() {
    }

    public LoaiGiay(int maLoaiGiay) {
        this.maLoaiGiay = maLoaiGiay;
    }

    public LoaiGiay(int maLoaiGiay, String tenLoaiGiay, Set<Giay> giays) {
        this.maLoaiGiay = maLoaiGiay;
        this.tenLoaiGiay = tenLoaiGiay;
        this.giays = giays;
    }

    @Id
    @Column(name = "MaLoaiGiay", unique = true, nullable = false)
    public int getMaLoaiGiay() {
        return this.maLoaiGiay;
    }

    public void setMaLoaiGiay(int maLoaiGiay) {
        this.maLoaiGiay = maLoaiGiay;
    }

    @Column(name = "TenLoaiGiay")
    public String getTenLoaiGiay() {
        return this.tenLoaiGiay;
    }

    public void setTenLoaiGiay(String tenLoaiGiay) {
        this.tenLoaiGiay = tenLoaiGiay;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiGiay")
    public Set<Giay> getGiays() {
        return this.giays;
    }

    public void setGiays(Set<Giay> giays) {
        this.giays = giays;
    }

}
