package models;
// Generated Nov 19, 2019 8:38:44 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ThongTinCoBan generated by hbm2java
 */
@Entity
@Table(name="ThongTinCoBan"
    ,schema="dbo"
    ,catalog="JAVA_WEB"
)
public class ThongTinCoBan  implements java.io.Serializable {


     private int maGiay;
     private Giay giay;
     private String mauSac;
     private Integer kichCo;
     private String moTa;

    public ThongTinCoBan() {
    }

	
    public ThongTinCoBan(Giay giay) {
        this.giay = giay;
    }
    public ThongTinCoBan(Giay giay, String mauSac, Integer kichCo, String moTa) {
       this.giay = giay;
       this.mauSac = mauSac;
       this.kichCo = kichCo;
       this.moTa = moTa;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="giay"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="MaGiay", unique=true, nullable=false)
    public int getMaGiay() {
        return this.maGiay;
    }
    
    public void setMaGiay(int maGiay) {
        this.maGiay = maGiay;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Giay getGiay() {
        return this.giay;
    }
    
    public void setGiay(Giay giay) {
        this.giay = giay;
    }

    
    @Column(name="MauSac")
    public String getMauSac() {
        return this.mauSac;
    }
    
    public void setMauSac(String mauSac) {
        this.mauSac = mauSac;
    }

    
    @Column(name="KichCo")
    public Integer getKichCo() {
        return this.kichCo;
    }
    
    public void setKichCo(Integer kichCo) {
        this.kichCo = kichCo;
    }

    
    @Column(name="MoTa")
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }




}


